name: Refresh Artist Metrics (All Platforms)

on:
  workflow_dispatch:    # Manual trigger from GitHub UI
  schedule:
    - cron: '0 2 * * *' # Runs daily at 02:00 UTC — adjust if needed

jobs:
  refresh:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      MIXCLOUD_CLIENT_ID: ${{ secrets.MIXCLOUD_CLIENT_ID }}
      MIXCLOUD_CLIENT_SECRET: ${{ secrets.MIXCLOUD_CLIENT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Refresh Spotify Metadata
        run: node backend/scrapers/refreshSpotifyMetadata.js

      # Placeholder for Mixcloud refresh (future)
      - name: Refresh Mixcloud Metadata
        run: |
          echo "Mixcloud refresh not yet implemented."

      # Placeholder for SoundCloud refresh (future)
      - name: Refresh SoundCloud Metadata
        run: |
          echo "SoundCloud refresh not yet implemented."
