name: Refresh Artist Metrics (All Platforms)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Run Spotify Refresh
        run: node scrapers/refreshSpotifyMetadata.js
        working-directory: backend

      # Placeholder for Mixcloud refresh (future)
      - name: Refresh Mixcloud Metadata
        run: |
          echo "Mixcloud refresh not yet implemented."

      # Placeholder for SoundCloud refresh (future)
      - name: Refresh SoundCloud Metadata
        run: |
          echo "SoundCloud refresh not yet implemented."
